version: '3.8'

services:
  app:
    build:
      context: .
    ports:
      - 8080:8080
    environment:
      - MONGO_URI=mongodb://mongo:27018/loans
    depends_on:
      - mongo
  mongo:
    image: mongo:latest
    ports:
      - 27018:27018
    volumes:
      - mongo-data:/data/db

volumes:
  mongo-data:
