name: ci

on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4

      - name: Set up MongoDB Memory Server
        uses: neofinancial/mongo-memory-server-action@v1.0.2
        with:
          db-connection-env-var: mongodb://localhost:27017
          run-command: bun run test
          binary-version: 7.0.5
          instance-dbName: test
          instance-port: 27017
          instance-storageEngine: wiredTiger
          mongoms-debug: 1

      - name: setup bun
        uses: oven-sh/setup-bun@v2

      - name: install dependencies
        run: bun install

      - name: run tests
        run: bun run test
