name: ci

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        distro: [ubuntu-24.04]
    steps:
      - name: Load libssl cache
        id: cache-ssl
        uses: actions/cache@v4
        with:
          path: ~/ssl
          key: libssl1.1

      - name: Install libssl1.1
        run: |
          mkdir -p ~/ssl && cd ~/ssl
          wget -nc https://ftp.debian.org/debian/pool/main/o/openssl/libssl1.1_1.1.1w-0+deb11u1_amd64.deb
          sudo dpkg -i libssl1.1_1.1.1w-0+deb11u1_amd64.deb

      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Bun
        uses: oven-sh/setup-bun@v2

      - name: Install dependencies
        run: bun install

  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        distro: [ubuntu-24.04]
    needs: build
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Bun
        uses: oven-sh/setup-bun@v2

      - name: Install dependencies
        run: bun install

      - name: Run tests with coverage
        run: bun run test --coverage

      - name: Upload coverage report
        uses: codecov/codecov-action@v2
        with:
          files: ./coverage/lcov.info
          flags: unittests
          name: codecov-umbrella

